# Generated by Django 5.1.6 on 2025-06-02 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Designates whether this customer can also sell products.'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='The user selling this product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_for_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Unique URL-friendly identifier for the product. Will be auto-generated if left blank by seller.', max_length=200),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['seller'], name='shop_produc_seller__500d4b_idx'),
        ),
    ]
